apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-svc-deployment
spec:
  selector:
    matchLabels:
      app: ui-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-svc
    spec:
      containers:
      - name: ui-svc-container
        image: cinnyabraham06/externalapp:8
        env:
          - name: SERVER
            value: 'http://demo-data-svc:8888'
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
